spec:
  name: n8n-test
  region: ams3

  services:
    - name: n8n
      image:
        registry_type: GHCR
        registry: ghcr.io
        repository: n8n-io/n8n
        tag: "1.116.2"
      http_port: 5678
      instance_count: 1
      instance_size_slug: apps-s-1vcpu-1gb

      health_check:
        http_path: /healthz
        initial_delay_seconds: 60
        period_seconds: 10
        timeout_seconds: 3
        success_threshold: 1
        failure_threshold: 3

      envs:
        # Database Configuration (PostgreSQL)
        - key: DB_TYPE
          value: postgresdb
        - key: DB_POSTGRESDB_HOST
          value: ${n8n-db.HOSTNAME}
        - key: DB_POSTGRESDB_PORT
          value: ${n8n-db.PORT}
        - key: DB_POSTGRESDB_DATABASE
          value: ${n8n-db.DATABASE}
        - key: DB_POSTGRESDB_USER
          value: ${n8n-db.USERNAME}
        - key: DB_POSTGRESDB_PASSWORD
          value: ${n8n-db.PASSWORD}

        # SSL Configuration for PostgreSQL (required for DigitalOcean managed databases)
        - key: DB_POSTGRESDB_SSL_ENABLED
          value: "true"
        - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
          value: "false"

        # n8n Configuration
        - key: N8N_HOST
          value: ${APP_URL}
        - key: N8N_PROTOCOL
          value: https
        - key: N8N_PORT
          value: "5678"
        - key: WEBHOOK_URL
          value: https://${APP_URL}/

        # Security - IMPORTANT: Change this value!
        - key: N8N_ENCRYPTION_KEY
          value: CHANGE_THIS_TO_RANDOM_STRING
          scope: RUN_TIME
          type: SECRET

        # User folder for n8n data
        - key: N8N_USER_FOLDER
          value: /home/node/.n8n

        # Disable telemetry
        - key: N8N_DIAGNOSTICS_ENABLED
          value: "false"

        # Timezone
        - key: GENERIC_TIMEZONE
          value: Europe/Amsterdam
        - key: TZ
          value: Europe/Amsterdam

        # Task Runner Configuration (disabled for simpler deployment)
        - key: N8N_RUNNERS_ENABLED
          value: "false"

  databases:
    - name: n8n-db
      engine: PG
      version: "17"
      production: false
      cluster_name: n8n-db
