# n8n Queue Mode Deployment
# For 100-1000 workflows/day, scalable production use
# Cost: ~$54/month base (Main + 1 Worker + PostgreSQL + Redis)
#
# Deploy with: doctl apps create --spec .do/examples/queue-mode.yaml
# Scale workers: doctl apps update YOUR_APP_ID --spec <updated-spec>

name: n8n-queue-mode
region: ams

# Main Service - UI, API, Webhooks
services:
  - name: n8n-main
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: n8n-io/n8n
      tag: "1.122.2"
    http_port: 5678
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    health_check:
      http_path: /healthz
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    envs:
      # Database Configuration (PostgreSQL)
      # Use DATABASE_URL which includes SSL configuration automatically
      - key: DATABASE_URL
        value: ${n8n-postgres.DATABASE_URL}

      # Queue Mode Configuration
      - key: EXECUTIONS_MODE
        value: queue
      - key: QUEUE_BULL_REDIS_HOST
        value: ${n8n-redis.HOSTNAME}
      - key: QUEUE_BULL_REDIS_PORT
        value: ${n8n-redis.PORT}
      - key: QUEUE_BULL_REDIS_PASSWORD
        value: ${n8n-redis.PASSWORD}
      - key: QUEUE_BULL_REDIS_TLS
        value: "true"

      # n8n Configuration
      # WEBHOOK_URL overrides N8N_HOST + N8N_PROTOCOL for external URLs
      - key: WEBHOOK_URL
        value: ${APP_URL}/
      # App Platform runs behind a reverse proxy
      - key: N8N_PROXY_HOPS
        value: "1"

      # Security - CHANGE THESE!
      - key: N8N_ENCRYPTION_KEY
        value: CHANGE_THIS_TO_RANDOM_STRING
        scope: RUN_TIME
        type: SECRET

      # Timezone
      - key: GENERIC_TIMEZONE
        value: Europe/Amsterdam

      # ⚠️ PRODUCTION STORAGE: Configure Spaces for persistent file storage
      # App Platform uses ephemeral storage - files are lost on container restart
      #
      # REQUIRED for production if you:
      # - Handle file uploads/downloads in workflows
      # - Use custom community nodes
      # - Process binary data (images, PDFs, etc.)
      #
      # Setup: See PRODUCTION.md#persistent-storage-critical-for-production
      # Quick setup (5 min):
      #   1. Create Spaces bucket via DigitalOcean Control Panel
      #   2. doctl spaces keys create n8n-storage-key
      #   3. Uncomment and configure variables below
      #
      # Cost: $5/month for 250GB + $0.02/GB thereafter
      #
      # - key: N8N_DEFAULT_BINARY_DATA_MODE
      #   value: filesystem
      # - key: AWS_ACCESS_KEY_ID
      #   value: YOUR_SPACES_ACCESS_KEY
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: AWS_SECRET_ACCESS_KEY
      #   value: YOUR_SPACES_SECRET_KEY
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: AWS_S3_BUCKET_NAME
      #   value: n8n-storage-ams3
      # - key: AWS_S3_ENDPOINT
      #   value: https://ams3.digitaloceanspaces.com
      # - key: AWS_S3_FORCE_PATH_STYLE
      #   value: "true"

# Worker - Executes Workflows
workers:
  - name: n8n-worker
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: n8n-io/n8n
      tag: "1.122.2"
    instance_count: 1  # Scale this: 1-10 based on load
    instance_size_slug: apps-s-1vcpu-1gb

    # Critical: Run in worker mode
    run_command: n8n worker

    envs:
      # Database Configuration (PostgreSQL)
      # Use DATABASE_URL which includes SSL configuration automatically
      - key: DATABASE_URL
        value: ${n8n-postgres.DATABASE_URL}

      # Queue Mode Configuration
      - key: EXECUTIONS_MODE
        value: queue
      - key: QUEUE_BULL_REDIS_HOST
        value: ${n8n-redis.HOSTNAME}
      - key: QUEUE_BULL_REDIS_PORT
        value: ${n8n-redis.PORT}
      - key: QUEUE_BULL_REDIS_PASSWORD
        value: ${n8n-redis.PASSWORD}
      - key: QUEUE_BULL_REDIS_TLS
        value: "true"
      - key: QUEUE_HEALTH_CHECK_ACTIVE
        value: "true"

      # Worker Concurrency (jobs per worker)
      - key: N8N_CONCURRENCY_PRODUCTION_LIMIT
        value: "10"

      # Security - SAME AS MAIN!
      - key: N8N_ENCRYPTION_KEY
        value: CHANGE_THIS_TO_RANDOM_STRING
        scope: RUN_TIME
        type: SECRET

      # Persistent File Storage (SAME AS MAIN!)
      # Uncomment if using Spaces (must match main service configuration)
      # - key: N8N_DEFAULT_BINARY_DATA_MODE
      #   value: filesystem
      # - key: AWS_ACCESS_KEY_ID
      #   value: YOUR_SPACES_ACCESS_KEY
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: AWS_SECRET_ACCESS_KEY
      #   value: YOUR_SPACES_SECRET_KEY
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: AWS_S3_BUCKET_NAME
      #   value: n8n-storage-ams3
      # - key: AWS_S3_ENDPOINT
      #   value: https://ams3.digitaloceanspaces.com
      # - key: AWS_S3_FORCE_PATH_STYLE
      #   value: "true"

# Databases
databases:
  - name: n8n-postgres
    engine: PG
    version: "17"
    production: true
    cluster_name: n8n-postgres

  - name: n8n-redis
    engine: VALKEY
    version: "8"
    production: true
    cluster_name: n8n-redis
