# n8n with Task Runners
# For apps using JavaScript/Python Code nodes with sandboxing
# No queue mode - single instance with runners
# Cost: ~$39/month (Main + 1 Runner + PostgreSQL)
#
# Deploy with: doctl apps create --spec .do/examples/with-runners.yaml

name: n8n-with-runners
region: ams

# Main Service - UI, API, Webhooks, Workflow Execution
services:
  - name: n8n
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: n8n-io/n8n
      tag: "1.116.2"
    http_port: 5678
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    health_check:
      http_path: /healthz
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    envs:
      # Database Configuration (PostgreSQL)
      # Use DATABASE_URL which includes SSL configuration automatically
      - key: DATABASE_URL
        value: ${n8n-postgres.DATABASE_URL}

      # n8n Configuration
      # WEBHOOK_URL overrides N8N_HOST + N8N_PROTOCOL for external URLs
      - key: WEBHOOK_URL
        value: ${APP_URL}/
      # App Platform runs behind a reverse proxy
      - key: N8N_PROXY_HOPS
        value: "1"

      # Security - CHANGE THIS!
      - key: N8N_ENCRYPTION_KEY
        value: CHANGE_THIS_TO_RANDOM_STRING
        scope: RUN_TIME
        type: SECRET

      # Task Runner Configuration (ENABLED)
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_RUNNERS_MODE
        value: external
      - key: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
        value: 0.0.0.0
      - key: N8N_RUNNERS_AUTH_TOKEN
        value: CHANGE_THIS_RUNNER_TOKEN
        scope: RUN_TIME
        type: SECRET

      # Timezone
      - key: GENERIC_TIMEZONE
        value: Europe/Amsterdam

      # Persistent File Storage - RECOMMENDED for production
      # Setup: doctl spaces keys create n8n-storage-key
      #        Create a Spaces bucket with name n8n-storage-ams3
      # See PRODUCTION.md#persistent-storage-critical-for-production
      - key: N8N_DEFAULT_BINARY_DATA_MODE
        value: filesystem
      - key: AWS_ACCESS_KEY_ID
        value: YOUR_SPACES_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        value: YOUR_SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AWS_S3_BUCKET_NAME
        value: n8n-storage-ams3
      - key: AWS_S3_ENDPOINT
        value: https://ams3.digitaloceanspaces.com
      - key: AWS_S3_FORCE_PATH_STYLE
        value: "true"

# Task Runners - Execute JavaScript/Python Code
workers:
  - name: n8n-runner
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: n8n-io/runners
      tag: "1.116.2"
    instance_count: 1  # Scale based on Code node usage
    instance_size_slug: apps-s-1vcpu-1gb

    envs:
      # Connect to main n8n instance
      - key: N8N_RUNNERS_TASK_BROKER_URI
        value: http://n8n:5679
      - key: N8N_RUNNERS_AUTH_TOKEN
        value: CHANGE_THIS_RUNNER_TOKEN
        scope: RUN_TIME
        type: SECRET

# Database
databases:
  - name: n8n-postgres
    engine: PG
    version: "17"
    production: true
    cluster_name: n8n-postgres
